server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ai_bot_platform?currentSchema=public
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL92Dialect
    show-sql: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: true

okhttp:
  connect-timeout-seconds: 30
  read-timeout-seconds: 30
  write-timeout-seconds: 30